version: '3'
services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    command: "npm run dev"

  backend:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 文字コード変更
    platform: linux/x86_64
    volumes:
      - ./backend/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"